CREATE TABLE INSTRUMENT_PRICE_MODIFIER (
  id bigint primary key auto_increment,
  name varchar(100) not null unique,
  multiplier number(10,4) not null
);

INSERT INTO INSTRUMENT_PRICE_MODIFIER (NAME, MULTIPLIER) VALUES ('INSTRUMENT1', 1.8876);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (NAME, MULTIPLIER) VALUES ('INSTRUMENT2', 2.2234);
INSERT INTO INSTRUMENT_PRICE_MODIFIER (NAME, MULTIPLIER) VALUES ('INSTRUMENT10', 3.8766);